export const GET_CHART_DATA = 'GET_CHART_DATA';
export const GET_CHART_DATA_ERROR = 'GET_CHART_DATA_ERROR';
export const GET_CHART_DATA_SUCCESS = 'GET_CHART_DATA_SUCCESS';
export const UPDATE_STATE_CHART_DATA = 'UPDATE_STATE_CHART_DATA';
