export const GET_DATA_COLLECTION = 'GET_DATA_COLLECTION';
export const GET_DATA_COLLECTION_ERROR = 'GET_DATA_COLLECTION_ERROR';
export const GET_DATA_COLLECTION_SUCCESS = 'GET_DATA_COLLECTION_SUCCESS';
