export const GET_DATA_COLLECTION = 'GET_DATA_COLLECTION';
export const GET_DATA_COLLECTION_ERROR = 'GET_DATA_COLLECTION_ERROR';
export const GET_DATA_COLLECTION_SUCCESS = 'GET_DATA_COLLECTION_SUCCESS';
export const EXPORT_DATA_COLLECTION = 'EXPORT_DATA_COLLECTION';
export const EXPORT_DATA_COLLECTION_ERROR = 'EXPORT_DATA_COLLECTION_ERROR';
export const EXPORT_DATA_COLLECTION_SUCCESS = 'EXPORT_DATA_COLLECTION_SUCCESS';
export const UPDATE_STATE = 'UPDATE_STATE';
