export const GET_SENSOR = 'GET_SENSOR';
export const GET_SENSOR_ERROR = 'GET_SENSOR_ERROR';
export const GET_SENSOR_SUCCESS = 'GET_SENSOR_SUCCESS';
export const UPDATE_STATE_SENSOR = 'UPDATE_STATE_SENSOR';
