export const GET_SENSOR_INFO = 'GET_SENSOR_INFO';
export const GET_SENSOR_INFO_ERROR = 'GET_SENSOR_INFO_ERROR';
export const GET_SENSOR_INFO_SUCCESS = 'GET_SENSOR_INFO_SUCCESS';
export const UPDATE_SENSOR_INFO = 'UPDATE_SENSOR_INFO';
export const UPDATE_SENSOR_INFO_ERROR = 'UPDATE_SENSOR_INFO_ERROR';
export const UPDATE_SENSOR_INFO_SUCCESS = 'UPDATE_SENSOR_INFO_SUCCESS';
export const UPDATE_STATE_SENSOR_INFO = 'UPDATE_STATE_SENSOR_INFO';
