export const GET_SETTING = 'GET_SETTING';
export const GET_SETTING_ERROR = 'GET_SETTING_ERROR';
export const GET_SETTING_SUCCESS = 'GET_SETTING_SUCCESS';
export const UPDATE_SETTING = 'UPDATE_SETTING';
export const UPDATE_SETTING_ERROR = 'UPDATE_SETTING_ERROR';
export const UPDATE_SETTING_SUCCESS = 'UPDATE_SETTING_SUCCESS';
