export const GET_DEVICE = 'GET_DEVICE';
export const GET_DEVICE_ERROR = 'GET_DEVICE_ERROR';
export const GET_DEVICE_SUCCESS = 'GET_DEVICE_SUCCESS';
export const UPDATE_STATE_DEVICE = 'UPDATE_STATE_DEVICE';
