export const GET_ALL_ALGORITHM_PARAMETER = 'GET_ALL_ALGORITHM_PARAMETER';
export const GET_ALL_ALGORITHM_PARAMETER_ERROR = 'GET_ALL_ALGORITHM_PARAMETER_ERROR';
export const GET_ALL_ALGORITHM_PARAMETER_SUCCESS = 'GET_ALL_ALGORITHM_PARAMETER_SUCCESS';
