export const GET_COMPARISION_PAGE_SETTING = 'GET_COMPARISION_PAGE_SETTING';
export const GET_COMPARISION_PAGE_SETTING_ERROR = 'GET_COMPARISION_PAGE_SETTING_ERROR';
export const GET_COMPARISION_PAGE_SETTING_SUCCESS = 'GET_COMPARISION_PAGE_SETTING_SUCCESS';
export const UPDATE_STATE_COMPARISION_PAGE = 'UPDATE_STATE_COMPARISION_PAGE';
