export const GET_DISPLAYED_DEVICES = 'GET_DISPLAYED_DEVICES';
export const GET_DISPLAYED_DEVICES_ERROR = 'GET_DISPLAYED_DEVICES_ERROR';
export const GET_DISPLAYED_DEVICES_SUCCESS = 'GET_DISPLAYED_DEVICES_SUCCESS';
export const RESET_DASHBOARD = 'RESET_DASHBOARD';
