export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICES_ERROR = 'GET_DEVICES_ERROR';
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS';
export const RESET_DASHBOARD = 'RESET_DASHBOARD';
