export const GET_DEVICE_INFO = 'GET_DEVICE_INFO';
export const GET_DEVICE_INFO_ERROR = 'GET_DEVICE_INFO_ERROR';
export const GET_DEVICE_INFO_SUCCESS = 'GET_DEVICE_INFO_SUCCESS';
export const UPDATE_DEVICE_INFO = 'UPDATE_DEVICE_INFO';
export const UPDATE_DEVICE_INFO_ERROR = 'UPDATE_DEVICE_INFO_ERROR';
export const UPDATE_DEVICE_INFO_SUCCESS = 'UPDATE_DEVICE_INFO_SUCCESS';
export const UPDATE_STATE_DEVICE_INFO = 'UPDATE_STATE_DEVICE_INFO';
